- defaults:
  link:
    relink: true

- clean:
  ~/:
    force: true
  ~/.config:
    force: true
    recursive: true
  ~/.aws:
    force: true
    recursive: true
  ~/.hammerspoon/:
    force: true
    recursive: true
  ~/.gnupg:
    force: true
    recursive: true

- link:

  # Public Configs
  ~/.aws/config: ./config/aws/config
  ~/.config/fish/config.fish: ./config/fish/config.fish
  ~/.config/gh/config.yml: ./config/github/config.yml
  ~/.config/kitty/kitty.conf: ./config/kitty/kitty.conf
  ~/.config/neofetch/config.conf: ./config/neofetch/config.conf
  ~/.config/starship.toml: ./config/starship/starship.toml
  ~/.gitconfig: ./config/git/.gitconfig
  ~/.gnupg/gpg-agent.conf: ./config/gnupg/gpg-agent.conf
  ~/.hammerspoon/init.lua: ./config/hammerspoon/init.lua
  ~/.config/spacebar/spacebarrc: ./config/spacebar/spacebarrc
  ~/.skhdrc: ./config/skhdrc/.skhdrc
  ~/.yabairc: ./config/yabai/.yabairc

  # Encrypted Config
  ~/.aws/credentials: ./secrets/decrypted/aws/credentials
  ~/.clasprc.json: ./secrets/decrypted/google-app-scripts/.clasprc.json
  ~/.config/gh/hosts.yml: ./secrets/decrypted/github/hosts.yml
  ~/.npmrc: ./secrets/decrypted/npm/.npmrc

  # Recovery Codes
  ~/auth/recovery-codes/discord.txt: ./secrets/decrypted/recovery-codes/discord.txt
  ~/auth/recovery-codes/github.txt: ./secrets/decrypted/recovery-codes/github.txt
  ~/auth/recovery-codes/npm.txt: ./secrets/decrypted/recovery-codes/npm.txt
  ~/auth/recovery-codes/twilio.txt: ./secrets/decrypted/recovery-codes/twilio.txt

  # Service Accounts
  ~/auth/google-service-accounts/bread-ai.json: ./secrets/decrypted/google-service-accounts/bread-ai.json
  ~/auth/google-service-accounts/intellibus.json: ./secrets/decrypted/google-service-accounts/intellibus.json

- shell:
    - [git submodule update --init --recursive, Installing submodules]
